name: Release
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Build Package
        uses: ouuan/pkgbuild-action@master
        id: build-package
        with:
          path: pkgbuild/

      - name: Set pre-release tag
        run: git describe --long | sed 's/^/vcs_version=/;s/\([^-]*-g\)/r\1/' >> $GITHUB_ENV

      - name: Pre-release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build-package.outputs.pkgfile }}
          tag_name: ${{ env.vcs_version }}
          prerelease: true
